#!/bin/bash

echo "####Olá Alex, vamos começar?###"

echo "Você gostaria de instalar seus programas padrões?  Digite 1)Sim  0)Não"
read ESCOLHA #aguarda opção inserida pelo usuário

if [ "$ESCOLHA" -eq 1 ]; then  #analisa a escolha digitada pelo usuário

    sudo apt upgrade -y  
    sudo apt update 
    sudo apt-get dist-upgrade -y
    sudo apt-get -f install
    sudo apt-get autoremove -y
    sudo apt-get autoclean
    #comandos de atualização
    sudo snap install code --classic 
    apt-get install git
    sudo snap install discord
    sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release


   

    
    sleep 1 #aguardar 1 segundo depois exibe a mensagem abaixo
    echo "Feito Alex, tenha um bom dia!"
else
    echo "Falha ao realizar as devidas instalações"
    sleep 2
fi
